name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CI: true 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build libs and test-app
        run: yarn build

      - name: Unit tests
        run: yarn test
      